name: Trigger auto deployment for container-app-mzhlqumqi2c4m

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-mzhlqumqi2c4m-AutoDeployTrigger-b125c602-462e-4b67-a003-24a5ead04367.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPMZHLQUMQI2C4M_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPMZHLQUMQI2C4M_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPMZHLQUMQI2C4M_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: defaultacrcontainerregistry8dfd.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPMZHLQUMQI2C4M_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPMZHLQUMQI2C4M_REGISTRY_PASSWORD }}
          containerAppName: container-app-mzhlqumqi2c4m
          resourceGroup: todonodejspgsqlgoogleauthbb259156
          imageToBuild: defaultacrcontainerregistry8dfd.azurecr.io/container-app-mzhlqumqi2c4m:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


